sudo: false
language: ruby
global:
  - GH_REF: git@github.com:YXQ212526/testapi.git
#  - secure: f/HAaX1kaw25du3nj2Lqo2+4P7YNo7jIqMDXC2XTAYdTMpXgZwo66zH8O0zi4TMQBG6FjtVX1/reTKioMKTV3MG65n5U

branches:
only:
  - master
cache: bundler
before_script:
  - git config --global user.name "crystal"
  - git config --global user.email "crystal@legenddigital.cn"
  - git clone https://${GH_TOKEN}@${GH_REF} -b gh-pages --depth=1 build
script:
  - bundle exec middleman build --clean
after_script:
  - cd ./build
  - git add .
  - git commit -m "update page automatically"
  - git push